const mongoose = require("mongoose");

const jobSchema = {
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  jobNumber: String,
  address: String,
  date: String,
  latitude: Number,
  longitude: Number,
  elevation: Number,
  wRegion: String,
  tc: String,
  lee: Number,
  leeZone: String,
  WSpeed: Number,
  ari: Number,
  shedType: [],
  IL: [],
  length: Number,
  width: Number,
  chlength: Number,
  chwidth: Number,
  noOfBays: Number,
  noOfColInMiddleBay: Number,
  NoOfColInEndBay: Number,
  MaxHeight: Number,
  roofType: [],
  RoofPitch: Number,
  condition: [],
  windSpeed: Number,
  snowZone: String,
  SElev: Number,
  RSnowLoad: Number,
  GSnowLoad: Number,
  windPressure1: Number,
  windCategory: String,
  rackingM: String,
  rackingE: Number,
  bayWidth: Number,
  RackForceHeight: Number,
  upliftMiddleMiddle: Number,
  upliftMiddleEnd: Number,
  selected: [],
  PSize: [],
  RSize: [],
  RESize: [],
  IFb: [],
  ISi: [],
  GFb: [],
  GSi: [],
  Fb: [],
  Eq: [],
  Db: [],
  MPi: [],
  EPi: [],
  b2: [],
  calcs: [],
  cer: [],
  IInfo: [],
  PDisplay: [],
  ReDisplay: [],
  PeDisplay: [],
  PiDisplay: [],
  RDisplay: [],
  InDisplay: [],
  InSideDisplay: [],
  BI: [],
  BE: [],
  BProp: [],
  IFBAuto: [],
  ISIAuto: [],
  PrSize: [],
  PropQ: [],
  Dl: Number,
  Ll: Number,
  Wu: Number,
  Wd: Number,
  Snd: Number,
  Snl: Number,
  PSpacing: Number,
  RSpacing: Number,
  PSpan: Number,
  RSpan: Number,
  PDepthI: Number,
  PDepthE: Number,
  moisture: String,
  d: Number,
  b: Number,
  grade: String,
  PProperties: [],
  PAnalysis: [],
  RafterCapacity: [],
  RafterCapacityE: [],
  IntermediateFrontBack: [],
  IntermediateSIDES: [],
  GirtsFrontBack: [],
  GirtsSides: [],
  PoleDesignInternal: [],
  PoleDesignExternal: [],
  BRes: Number,
  TRes: Number,
  Blocking: Number,
  MomentLong: Number, // applied
  MomentMedium: Number, // applied
  MomentShort: Number, // applied
  Momentupshort: String, // capacity
  MomentDownmedium: String, // capacity
  MomentDownlong: String, //capacity
  EqZone: Number,
  DZone: String,
  MaxGirtSpan: Number,
  engineer: String,
  engineerDescription: String,
  registrationNumber: String,
  phoneNumber: String,
  engineerEmail: String,
  engineerCompany: String,
  companyaddress: String,
  clientCompany: String,
  pdfUrl: String,
};

module.exports = mongoose.model("Job", jobSchema);
